name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Run on new tags

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: mkdir build
    - run: cmake .. -DRAKNET_ENABLE_SAMPLES=0
      working-directory: build
    - run: make
      working-directory: build
